services:
  - type: web
    name: portal-barrios-privados
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: .
      - key: DATABASE_URL
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
